# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool: 'Default'

variables:
  phpVersion: 8.1

steps:
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://192.168.40.130:8444/scancentral-ctrl/'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://fortify01:8443/ssc'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    buildFailureCriteria: '[fortify priority order]:critical'
    timeoutForPollingArtifactState: 30
    autoDetectBuildTool: true
